{
 "title": "Node Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_list", "label": "Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Number of PUTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "safenode_put_record_ok_total{node_id=~\"$node_list\"}",
     "legendFormat": "{{node_id}} {{record_type}}"
    }
   ]
  },
  {
   "title": "New connections per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_swarm_connections_established_total{node_id=~\"$node_list\"}[$__rate_interval])",
     "legendFormat": "{{node_id}} {{role}} {{protocols}}"
    }
   ]
  },
  {
   "title": "Currently Established Connections",
   "type": "timeseries",
   "description": "The number of connections established by the node at a given moment. \nDialer - the node opened the connection\nListener - the connection was opened with the node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "libp2p_swarm_connections_established_total{node_id=~\"$node_list\"} - sum without(cause) (libp2p_swarm_connections_duration_seconds_count{node_id=~\"$node_list\"})",
     "legendFormat": "{{node_id}} {{role}} {{protocols}}"
    }
   ]
  },
  {
   "title": "Number of Peers in Routing Table",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "safenode_peer_added_to_routing_table_total{node_id=~\"$node_list\"} - safenode_peer_removed_from_routing_table_total{node_id=~\"$node_list\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Time to establish 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, protocols) (rate(libp2p_swarm_connections_establishment_duration_bucket{node_id=~\"$node_list\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}